travis:
  secure:
    BINSTAR_TOKEN: Z8N7Aq9I+30E0nWs5kPRDULLjOweERYbKKXFlvDD9QhIsH6TROiclzgw0a7D4up6/S44xDiwT54//IoB9eSGsL8oE4GzNQABQY3hi/4vn3CQZAg4h2pbzkMhsXBwKEU44c7vjkEAch8JausW2YQomqCFS/ncS3Df3R1CkG0DAxzv2hejFUqc7GUh5avmA7dBYCkONpFy7l925rrz4J5u7EcN7mP4k9bFLn/YWufQ80yEqfiGF7GJBMUq6ULqdCxgSoZ42khIVcY7OICqKV6tRkL6LgORcand+k6CvTpkEmiJOnkCF0j3VRnc+Gc4znpOzxTI6icaCXBygy7lfo9TPcquwAWFohcWQ5A7jh86cLB8aQVhFBQKhLC6xK1aDzssuoq+5qF0oVQgDrmCahi1iqJQVWX+9HWl48UgAGpKtjqYow2AEUjMOHqRtamEgz2wcJUG0PJ0hvSzxhQKf1BXvWXjCXQuX5Nm6+9rgAQr6qZTplFlCbpsN7MJW7AG5T/fH2V+KkUkaz6JVnlYv63gCkPCyz3S3aawQQS5O/7O457GEDWqDtvN8xBP6m5xCZE/u6hgJSiZ8qVj76G5ZvKTN4lLWQK+T+ZeFifKYMipquH0xrvR67iiHUixXC2hQWF4Pw4dDH3KEkj3YptjKs2jOS0Zro/h54/ykCbO4mk34h4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
