travis:
  secure:
    BINSTAR_TOKEN: tR33XZwqVaxond76VdfoYLipeoeAVpm8HVEeSVjmBMA4UJmpOM3fYGcFhkzcc2d+M2r6Zs6ASN0dVX4unQz4GktLE2CQBLRhouyc+Me02sr0pgI0AZWOtEw1T/OytXjVOAeZun5jS6MkmmHohb2JELXRTLPh6NJAkxOjIJj9RD+2op4klkvCZHs5tNzmCJ+MbNwvmNol6Bh/NtMVc0+s1HzyGNaIBVFf0ZtxNvA7SQRlKbOurl93XyMgXBKwhIQVPdPpIpWzYcQq/9SqZocUAbj8sjCiofdDBahlZJMKucQ3PizRAlR08xz4KD0ufPVGII9LD/piU9c6W0RygeGo5KrGBxNPTBkmmchsm9uTf/iIRjJIOhZVNZ9mFNz4r0ijoQS4ImB1+CYgh0Ya1IXtSbmyrdN/KSn054VCKVZV+O0o6fSooGl3WbDpp3j/FQc2p3jSCKHmiHdJTsHgA3XLQ4pjgyf8FpK+gNfIy2QwF1UcgUcGImq9S7kFtLxS2jdI8Xu699tbzrEqb4Lus8oPLh5S6N+p89eHLuJoKeqKgRummoWgmjjgKfDZh7+LKVEc5OT7b+Kjk9L5LR8J+M6M5MeId404D6JifioIWkt12u08ZwTD/kEWBrD/UJVX3Wh1zfbIUOUGfCemcxvSkquV+1BvxoIZGdr74rLS2TOCu5M=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
