travis:
  secure:
    BINSTAR_TOKEN: JsfXzDZ+naPIKDjvwyBqvgj9KawLW79jo1CdYlvdYTjQrmYDOWqk9/hVPNh/YeWRAZGbeV658Bxsr1ElDATZD9Gxx9FttN3j7FusR4uyoAmzyGI7l9U10BZSeIkNT4pOnC1g8Hu87VjBgpgFDlYq7JADjAi7uRQDDNhmXKm+M2nGH+LOAkH9DQS0uuGtD8wmr0jODppDPsI8p8HEisyGyHAY6PQfCSxidlDQ8EIQLvsYh6caIkIgLAt1fpcOjJOdUob6jqYb/hhcqg0I8VZnQ1Wdw64rUWGHCvhMKFc+lW7zyAWVtemGuZNOqJQxarTukj69J8y3R1ZG0LAejl2hi1X49hUZgDwkT14lI7ZjR+PsBW0Fd4hRCb5prPIeOUjAHJgxzve6ebI0iuNge2gWQF4EjpMRWCIWmKRsnWsNe8iR88x+dPFrabZzPZmtPpHlqQWm/yqMQCokkEchOcA+z0d2w+ZAeWxzeV90Di6YuGw7EKYYunVOez0Zo2DDQjmxwxZEHIUh/2JEDuJfKvHhJovgmMBfkC4gvil9Ni2PoKWnfsdWm7C8VheYRixRvobegm8m5I5QG6OGjnYw/mxgcWVSJi2JBg7oGBv+6RXt6gL4AkjNXeiawUy6AYkjV0tGiBc9ngxqf2UNrrEwT7ihY+ly5Y8Uu9Q8fuMhlbUpNAM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
