travis:
  secure:
    BINSTAR_TOKEN: fpLwQvyjgMkSZTRPaTlUwD/jlmMWHo3npNjgmcerbaopY84p50gQYedwAMOi+Ji5eddqAT9Xv1dJfBNaOFAMtGMtxn0Fb/BdDVUWD1dUQGCssfxZvPzu99Pd8EdkSeWfA7XqwsLE/FZRFTbAmwXIX0sUUv8jjN/Vk5ogR8rP3eTanSfwtfOnRJSBdXCL/Fm6O4H14J4Q9HG5PQA36gRfWyHSqv1bWgKr5rkDshfETLCQNRJwUVUaarMQHuX1DpGJamU9pylQ3f+fLanttwAKXzuCY3Lm0qn24AgtoCIV0Tx7dM0+vVKLxHHSwuimGlNLzlvNj7XeVjbF2w6WHPWN8tx8yf1UY7IdC1IuoeABiPalzTgaQ/Q1lX2vm+AxxIgoR5OwmfekJkU+lphzxPoDG+tVWL6maZlF2SmrprbEXrrie0Mz1Kp/K4FjSrbKiQPgqICaNx/sOdfX5ur3iBewJeMcPZWGMtioziSOaJBsenkUl8wtLua5v28CYLf28QR5fYLYxhYNQHjJ93iwEXthLKQ7HBq0WFmsycQ+GDUz3PrgQmfTaD/iFbs7wt/RAdvDwIVHw8lvG9p9HVAuNRtZyfo8VnbFKfYPn7sH/QNbxQM+9U76sYkzhYqP1hrMyOZVqQGTVwll+DeSo5twlkfNcFod9+aYbtumv/QeV0Gj6AM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
