travis:
  secure:
    BINSTAR_TOKEN: Z64ijfNZPe4BZxaquV0z/8NoJhW+UBQWflMyGfag1apdvao0nIxAmNSemJNISXGo437tNDE/cRaGZamfvuIuH4sSRP9j+7isQKmNPjsIUWY73osjaYFUvPE/lLMIfyy5XmxTHeJh5xOYSWvSZpuAR6Cs6CJnBOy3BbGE2aVqv/ILa8W7d2exmg3cjBiE2jp5gkI3iCjemKT2ljOFFb3c3btf1k9kw1KusYMCemPTQ4vbj/9406HB2RUI+MAFS+ukN9NH7h2C41WVxluw3AuXfUg293UZst7VLUIMKaYgsthlDgSdnO3WzaK0aD2weTfEh2K5nrVp7FK5nzZU6G6w+COr/Y3blwGq2ueAV14mibbfAXtLPHvoNz7S2u3Shei2UktliL6mQmz7JUVMIsG8HcHhiX1Qp9lisCF+i+u73kKR6wIMrfFyllT/LnofLH52mPOLIhA/A3uUnoS6+r2hvsnDia7wAZhtl825azVEYAcCHoWlvtHwzMM81LwaLO1nrYHOs0red3F20CC5rwNB+F4u+oMud99DpI080H/5MhyiNkM5IJu/MOCW/4kz5LnnkrWRRlzO1bFH+zLg3VnwlBXtr/zK92f0XdsmBgHdixtTK6QKI45KMCm8XcHvV2gdc8f3fOnL475hTYuPZYEwTg3ECGJ06+f6wqlNVx57WY4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
